language: php
php:
  - '7.1'
  - nightly

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

install:
  composer update -n $PREFER_LOWEST

jobs:
  include:
    - stage: test
      script: make lint
    - stage: test
      script: make stan
    - stage: test
      script: make test

stages:
  - test
