#!/usr/bin/env bash

IMAGE_NAME=wizaplace-php-sdk-env

if [ -z "$1" ]; then
    MAKE_ARGS="all"
else
    MAKE_ARGS="$1"
fi

APP_DIR="$(cd $(dirname $0) && pwd)"

docker build -t "${IMAGE_NAME}" .
docker run --rm -v "${APP_DIR}":/app -v composer-cache:/composer/cache -u $(id -u):$(id -g) --network=host "${IMAGE_NAME}" make "${MAKE_ARGS}"
