# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
      - stan:
          requires:
            - build
      - phpunit:
          requires:
            - build

jobs:
  build:
    docker:
      - image: circleci/php:7.1-cli
    working_directory: ~/repo
    steps:
      - checkout
      - run: ./.circleci/merge_master.sh
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo
  lint:
    docker:
      - image: circleci/php:7.1-cli
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: make lint
      - store_artifacts:
          path: phpcs
      - store_test_results:
          path: phpcs
  stan:
    docker:
      - image: circleci/php:7.1-cli
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: make stan
  phpunit:
    docker:
      - image: circleci/php:7.1-cli
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: make test
      - store_artifacts:
          path: phpunit
      - store_test_results:
          path: phpunit
